### PR TITLE
WIP - API redesign

### PR DESCRIPTION
**Pull request by asross**
Modified version of https://github.com/fhir-crucible/fhir_client/pull/21 that builds on @arscan 's work but focuses on making `client` accessible from all `FHIR::Model` instances, even deeply nested ones. Implements CRUD operations and also reading `FHIR::Reference`s from the same client.

I have not run the tests, which I think were still under development, and more tests will definitely be required before this is merge-able, but I wanted to open it up for consideration.

### CODE REVIEW

**Comment by bkaney** [comment]
What's your reasoning for moving `Bundle` into `lib/ext`, is this not the same concept as a FHIR Bundle and should stay in `models`?

**Comment by asross** [comment]
> What's your reasoning for moving Bundle into lib/ext, is this not the same concept as a FHIR Bundle and should stay in models?

Those are extensions to classes defined by `fhir_models`. However, it could maybe be moved to `lib/gem_ext/fhir_models`, I've seen that pattern before.

**Comment by bkaney** [comment]
> Those are extensions to classes defined by fhir_models. However, it could maybe be moved to lib/gem_ext/fhir_models, I've seen that pattern before.

Ah got it, yea `lib/gem_ext/fhir_models` seems more conventional.

**Comment by arscan** [comment]
Your suggestions on References, Bundles, & cascading the client down to child resources look good.  I started adding Exceptions today, and have been working on porting over a couple of our crucible test suites to use this new API to see if we are missing anything major.

I think the unresolved questions up to this point are:

1. Should we stick with more traditional ActiveRecord style methods (find, save, where), or diverge (read, update, search)?  I can see pros and cons of each.  I’ve been doing the ActiveRecord-style methods up to this point, which seems to be fine so far.   But I can see it being confusing if it is similar to ActiveRecord but not exactly the same.
2. Should we explicitly pass client in to each method call, or have a global configuration that can be overridden with an optional client parameter?  I’m trying out the latter right now, which is nice for us since we mostly just use one client, but it makes the code within the client a bit messier since I am dumping different kinds of objects in the options argument.

**Comment by asross** [comment]
> 1. Should we stick with more traditional ActiveRecord style methods (find, save, where), or diverge (read, update, search)? I can see pros and cons of each. I’ve been doing the ActiveRecord-style methods up to this point, which seems to be fine so far. But I can see it being confusing if it is similar to ActiveRecord but not exactly the same.

I've talked to a few folks here and it feels like the [FHIR REST spec](https://www.hl7.org/fhir/http.html) is already pretty syntactically straightforward, and it also feels like users of this gem should understand it before using it. Also, with ActiveRecord, there are multiple possible connection backends with different interfaces (mysql, postgresql, sqlite, mongodb, etc), so it makes more sense to insert a more abstract layer between that each connection adapter implements. Here, though, we've only got one backend (the FHIR server), and its API at this point is very stable. So it seems better to just mirror it directly, which also will prevent us from mixing metaphors when we implement vread.

> 2. Should we explicitly pass client in to each method call, or have a global configuration that can be overridden with an optional client parameter? I’m trying out the latter right now, which is nice for us since we mostly just use one client, but it makes the code within the client a bit messier since I am dumping different kinds of objects in the options argument.

You know, there's no reason not to have a global configuration option if it can always be overridden on class methods. In our use-case, we're building a SMART app that can connect to any EHR, and even for the same EHR each user has a different OAuth token, so we definitely need to always pass the client -- but it seems like the singleton client case won't be that uncommon so we should support setting a global client.

In your branch you also had a `format` configuration option, but I wasn't able to find where that was used. Shouldn't that information already be a property of `client`? I might definitely be missing something.

**Comment by asross** [comment]
Also, feel free to add `Vermonster/fhir_client` as another remote and keep working off of this branch if you want to make changes on top of this -- I can also update this PR if you want.

**Comment by arscan** [comment]
Sorry for the slow response -- I have been out for a couple of days.

You are correct, the ```format``` option should just be set in the client.  I had put that in but forgot to remove it once I realized that it didn't really make sense to include.

I'm good with basing method names off the FHIR rest spec.

Thanks for incorporating my earlier comments.  Just a few more thoughts:

1. Would it make sense to be able to optionally pass client into update, create, save?  We quite frequently do something like ```patient = FHIR::Patient.new(name: {given: 'Sam', family: 'Jones'})```, then ```patient.save```.  Seems a bit better to do ```patient.save(client)``` instead of ```patient.client = client```.

2. How should we handle things like [conditonal create](https://www.hl7.org/fhir/http.html#ccreate)?  Create a new method conditional_create, or should we give these methods a bit more flexibility by having an optional parameter that we can throw in extra data.  We probably don't want to make this API support everything in the FHIR spec (maybe just shoot for the most common cases), but I'm not exactly sure where we should draw that line yet.

**Comment by arscan** [comment]
Also, if we are moving away from the ActiveRecord methods, should we change the ```save``` instance method to ```create``` (and get rid of the id check)?

**Comment by arscan** [comment]
Another example of maybe needing an options param on all of these...  see _summary in the read method:  https://www.hl7.org/fhir/http.html#read

In what I had before, I would have passed ```summary: "text"``` in the options of ```read``` so I could then pass it along to the client.  But we don't have anywhere to handle something like that in here.  What do you think?

**Comment by arscan** [comment]
After playing around with it for awhile, I think we can keep it simple and do the way that you have it set up (instead of what I had suggested earlier with an options parameter).  I'll just create new methods that explicitly take the proper arguments when I run into situations like read summary and conditional create (```read_with_summary``` and ```conditional_create```, for example).  That seems better than having magic flags being passed in an options hash.  Plus having to do ```client: client``` all the time for you seems silly.

I tried to push up a couple of small fixes to this branch on this remote, but I don't have access.  Could you target this pull request for ```api-redesign``` on our repo, or give me write access to this?  (or am I doing something wrong here with github).

Thanks for your patience!

**Comment by asross** [comment]
@arscan gave you access, I can also close and reopen this PR to target `api-redesign` here if you want.

Agreed about defining new methods for the read summary/conditional create cases.

In terms of the `save` method, hmm... I re-added it because it seemed like, as opposed to naming choices like `read` vs. `find` or `search` vs. `where`, that `save` actually was doing something useful and different, so it merited separate definition, but I hadn't considered just adding a `create` instance method. We should definitely define `create`, and I guess I could go either way on having `save` as well.

For optionally passing `client` into instance methods, I'd be ok with it, but just have some questions about it. It seems like the case you're describing where it's most needed is for creating records, but in that case, you could just do `patient = FHIR::Patient.create({ name: {given: 'Sam', family: 'Jones'} }, client)` or even
 
```ruby
new_patient = FHIR::Patient.new(name: {given: 'Sam', family: 'Jones'})
persisted_patient = FHIR::Patient.create(new_patient, client)
```

Another option would be, if you are using the same client,

```ruby
FHIR::Model.client = client
patient = FHIR::Patient.new(name: {given: 'Sam', family: 'Jones'})
# do more intermediate stuff?
patient.create # or .save or .update
```

I'm having a hard time imagining when you'd ever do `patient.update(client)`, unless perhaps you're copying changes to a patient to multiple servers:

```ruby
[client1, client2, client3].each { |client| patient.update(client) }
```

Not sure if that's common, though.

**Comment by arscan** [comment]
Yeah, I'm fine leaving out that suggestion I had for passing client to the instance methods.  Doesn't seem worth it.

Could you just reopen this on ```api-redesign``` on our repo, and I'll get it merged in?  I'm still having access problems pushing a commit up onto here.  Thanks!

**Comment by asross** [comment]
Ok, will do!

**Pull request closed without merging**
