### PR TITLE
Don't use "_search" path component for GET-based search

### PR DESCRIPTION
**Pull request by jmandel**

### CODE REVIEW

**Comment by jmandel** [comment]
FHIR spec defines:

    GET /Patient
    POST /Patient/_search

http://hl7-fhir.github.io/http

**Comment by andrequina** [comment]
The actual issue is upstream during the selection of the HTTP method rather than building the URI.  See #11 which fixes the selection of GET vs. POST.

**Comment by jmandel** [comment]
@andrequina thanks for the upstream fix. Ideally the client would be able to handle search-by-get and search-by-post, to test both methods. Is this now the case?

**Comment by arscan** [comment]
@jmandel : If you pull down the update copy, you can now do the following:

```ruby
client = FHIR::Client.new('http://example.com')

client.search FHIR::Patient, search: { parameters: {name: 'John'}}               #get
client.search FHIR::Patient, search: { flag: true, parameters: {name: 'John'}}   #post

```

**Comment by jmandel** [comment]
Got it, thanks! Does "flag" have some meaning in this context that I'm
missing out on?

**Comment by andrequina** [comment]
I think flag is just a bad name.  I think we need to refactor that to something along the lines of isPost... I'll have to ask Jay about it when he is back in from vacation to see if there is any context to the name.

**Pull request closed without merging**
