### PR TITLE
Added the possibility to set a proxy URL for the client

### PR DESCRIPTION
**Pull request by EtienneDepaulis**
This PR adds an attribute `proxy_url` to the `FHIR::Client` object. It helps set up a proxy URL.

For the `RestClient` strategy, it was possible to define it after setting the strategy, for the `OAuth2::Client` it was needed inside in order to provide this configuration before retrieving the token.

### CODE REVIEW

**Comment by arscan** [comment]
Thanks for another contribution!

We have been simply using the `http_proxy` and `https_proxy` environment variables to handle proxies, which get picked up by the libraries we are using.  Is there a situation where this doesn't work?

**Comment by EtienneDepaulis** [comment]
Not a bad idea, I completely forgot about this feature :/ Thx for pointing it out :)

**Comment by EtienneDepaulis** [comment]
@arscan We identified an issue using the `HTTPS_PROXY` setting on Heroku : it looks like it is used during build time which prevents the app from being deployed :/
Therefore I would like to re-submit this PR as it can help avoid this kind of conflict on certain PaaS

**Comment by arscan** [comment]
Sure, since both RestClient and OAuthClient have a proxy attribute, it seems to make sense for this library to also.  Would you consider naming it `proxy` just to be consistent with those other two libraries we use?

And I just accepted PR #105, which creates a new client to resolve external references.  I assume we should have that client use the same proxy as this client.  Could you pull in those changes here (or rebase) and add in this proxy to that?

And finally, could you update the README with a quick blurb about this (just near the end is fine).

Thanks!

**Comment by EtienneDepaulis** [comment]
@arscan I've updated the naming convention in favor of `proxy` and added basic info in the Readme (I also included the `additional_headers` which was missing in the documentation).

As for #105 I'm not certain about how to tackle this problem. What about other settings ?

**Comment by arscan** [comment]
Thanks! I think you forgot to rename `proxy_url` to `proxy` in a few places though, since a bunch of tests are failing now.

And I was just referring to these two lines:
https://github.com/fhir-crucible/fhir_client/blob/master/lib/fhir_client/ext/reference.rb#L62
https://github.com/fhir-crucible/fhir_client/blob/master/lib/fhir_client/ext/reference.rb#L72

To follow external references we have to create a new client (because it is a new FHIR endpoint), and I would think we would want to set the proxy correctly on those new clients, or is that not necessary given the way that RestClient is referenced?

Also, I'm a bit confused about how this is used.  It doesn't seem like the proxy is set until you explicitly set an auth scheme (or set_no_auth)?    Just doing `client.proxy = 'http://xyz.com'` won't propagate the change to RestClient or OAuthClient, until something like `client.set_no_auth` is called?

**Comment by radamson** [comment]
Thanks for the contribution and updates!

**Comment by EtienneDepaulis** [comment]
Thx @radamson :)

**Pull request merged**
