### PR TITLE
Update Headers

### PR DESCRIPTION
**Pull request by radamson**
This removes unncessary headers (such as id, resource, and format) seen in the below request, and invalid headers (such as Content-Type being used with `GET` requests)
See: https://www.hl7.org/fhir/http.html#summary
screen shot 2018-11-09 at 2 00 11 pm

It also adds

- support for return preference headers where applicable

- functionality which can be used to normalize headers (which should be [case-insensitive](https://tools.ietf.org/html/rfc7230#section-3.2))

- Adds methods for conditional_read_since, conditional_read_version, and version_aware_update

Open to any suggestions or improvements to how this could be implemented

### CODE REVIEW

**Comment by arscan** [comment]
I think we'll need to fix the codeclimate issues (or mute them) because we shouldn't be merging PRs that fail travis.  Maybe this is happening because we are removing Ruby 2.2 support?

**Comment by arscan** [comment]
FYI @EtienneDepaulis.  Our intent here is to fix a bug that has been around in the gem for some time, without changing the behavior (besides getting rid of the bug), but since this touches a bit of code could you take a look to see if it makes sense to you and doesn't cause any issues for your use case?

**Comment by radamson** [comment]
It is [passing travis](https://travis-ci.org/fhir-crucible/fhir_client/builds/475093253?utm_source=github_status&utm_medium=notification), but I agree we should address the codeclimate issues

**Comment by arscan** [comment]
Alright, we'll go ahead and merge this in.  I'll bump up the minor version on release because this does change the behavior slightly, though it shouldn't affect anyone in theory.

**Pull request merged**
